name: Hansaka MD Bot 24/7

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # හැම පැය 5න්ම Auto Restart වෙනවා

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          npm init -y
          npm install telegraf

      - name: Run Bot
        run: node index.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OMDB_API: ${{ secrets.OMDB_API }}
